---
- name: Hello job
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 10
  rules:
    - name: Say Hello
      condition: event.i in [2,4,6]
      action:
        run_job_template:
          name: hello
          organization: Default
          
